HoBT/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # Django에서 지원하는 views 라이브러리를 활용 (로그인, 로그아웃, 비밀번호 찾기&초기화 등)
    # pybo.urls에서 연결되는 views.py 파일의 함수를 만들 필요가 없음(Django가 알아서 다 처리)
    path('login/', auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.signup, name="signup"),
    path('withdrawal/', views.withdrawal, name='withdrawal'),
]

HoBT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from hobt import views # pybo 디렉토리에 있는 views를 가져오기

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hobt/', include('hobt.urls')), # views의 index를 만들기
    path('common/', include('common.urls')),
    path('exam/', include('exam.urls')),
    path('', views.index, name="index"),
    path('hobt_dict/', include('hobt_dict.urls'))
]

HoBT/exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exam_judge/', views.exam_judge, name='exam_judge'),
    path('exam/', views.exam, name='exam'),
    path('exam_result/', views.exam_result, name='exam_result'),
    path('exam_select/', views.exam_select, name='exam_select')
]

HoBT/hobt_dict/urls.py
from django.urls import path
from . import views

app_name = 'hobt_dict'
urlpatterns = [
    path('', views.hobt_dict, name='hobt_dict'), # 문제 사전 게시판 메인 페이지
    # path('create/', views.HobtDictCreateView.as_view(), name='hobt_dict_create'), # 문제 등록 현재는 사용하지 않는기능
    path('<int:pk>/modify/', views.hobt_dict_modify, name='hobt_dict_modify'), # 문제 수정
    # path('<int:pk>/delete/', views.hobt_dict_delete, name='hobt_dict_delete'), # 문제 삭제
    path('like/<int:pk>/\\Z', views.hobt_dict_like, name='hobt_dict_like'), # 문제 추천
    path('<int:pk>/', views.hobt_dict_detail, name='hobt_dict_detail'), # 문제 상세보기
    path('hobt_search/', views.hobt_search, name='hobt_search'), # 검색기능
    path('cs_search/', views.cs_search, name='cs_search'), # 검색기능
    path('adsp_search/', views.adsp_search, name='adsp_search'), # 검색기능
    path('add_problem/', views.add_problem, name='add_problem'), # 사용자가 문제를 추가
    path('problem_list/', views.show_problems, name='problem_list'), # 사용자 및 관리자가 추가한 문제 검토 리스트
    path('add_selected_problems/', views.add_selected_problems, name='add_selected_problems'),
    path('delete_selected_problems/', views.delete_selected_problems, name='delete_selected_problems'), # 체크박스 선택 항목 삭제
    path('cs_dict/', views.cs_dict, name='cs_dict'),
    path('adsp_dict/', views.adsp_dict, name='adsp_dict'),
]

HoBT/hobt_dict/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.views import View
from django.contrib.auth.decorators import user_passes_test

from .models import HobtDict
from .forms import HobtDictForm


def hobt_dict(request):
    """
    문제 사전 게시판 메인 페이지
    """
    # 페이지네이션 기능 추가
    q = request.GET.get('q', '')  # 검색어
    page = request.GET.get('page', '1')  # 페이지

    hobt_dict_list = HobtDict.objects.order_by('-qid')
    if q:
        hobt_dict_list = hobt_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q)| Q(qid__icontains=q)
            | Q(small_category__icontains=q)| Q(big_category__icontains=q)| Q(appearance_date__icontains=q)
        ).distinct()

    paginator = Paginator(hobt_dict_list, 10)
    hobt_dicts = paginator.get_page(page)

    context = {'hobt_dicts': hobt_dicts, 'page': page, 'q': q}
    return render(request, 'hobt_dict/hobt_dict.html', context)


class HobtDictCreateView(View):
    """
    문제 등록
    """
    def get(self, request):
        form = HobtDictForm()
        return render(request, 'hobt_dict/hobt_dict_form.html', {'form': form})

    def post(self, request):
        form = HobtDictForm(request.POST)
        if form.is_valid():
            hobt_dict = form.save(commit=False)
            hobt_dict.author = request.user
            hobt_dict.save()
            messages.success(request, '문제가 등록되었습니다.')
            return redirect(hobt_dict)
        return render(request, 'hobt_dict/hobt_dict_form.html', {'form': form})


@login_required
@user_passes_test(lambda u: u.is_staff or u == hobt_dict.author)
def hobt_dict_modify(request, pk):
    """
    문제 수정
    """
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    if request.user != hobt_dict.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('hobt_dict:hobt_dict_detail', pk=hobt_dict.pk)

    if request.method == 'POST':
        form = HobtDictForm(request.POST, instance=hobt_dict)
        if form.is_valid():
            hobt_dict = form.save(commit=False)
            hobt_dict.author = request.user
            hobt_dict.save()
            form.save_m2m()  # ManyToManyField를 저장하는 데 필요
            messages.success(request, '문제가 수정되었습니다')
            return redirect(hobt_dict)
    else:
        form = HobtDictForm(instance=hobt_dict)
    context = {
        'form': form,
        'qid': hobt_dict.qid,
    }
    return render(request, 'hobt_dict/hobt_dict_modify.html', context)


@login_required(login_url='common:login')
def hobt_dict_delete(request, pk):
    """
    문제 삭제
    """
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    if request.user != hobt_dict.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        hobt_dict.delete()
        messages.success(request, '문제가 삭제되었습니다.')
        return redirect('hobt_dict:hobt_dict')


@login_required(login_url='common:login')
@require_POST
def hobt_dict_like(request, pk):
    """
    문제 추천
    """
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    if hobt_dict.like.filter(id=request.user.id).exists():
        # 이미 추천한 경우
        hobt_dict.like.remove(request.user)
        message = '추천을 취소했습니다.'
    else:
        # 추천하지 않은 경우
        hobt_dict.like.add(request.user)
        message = '문제를 추천했습니다.'
    context = {'like_count': hobt_dict.like.count(), 'message': message}
    return JsonResponse(context)


def hobt_dict_detail(request, pk):
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    context = {'hobt_dict': hobt_dict}
    return render(request, 'hobt_dict/detail.html', context)



def search(request):
    """
    문제 검색 기능
    """
    q = request.GET.get('q', '')  # 검색어
    page = request.GET.get('page', '1')  # 페이지

    hobt_dict_list = HobtDict.objects.order_by('-qid')
    if q:
        hobt_dict_list = hobt_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q) | Q(qid__icontains=q)
            | Q(small_category__icontains=q) | Q(big_category__icontains=q) | Q(appearance_date__icontains=q)
        ).distinct()

    paginator = Paginator(hobt_dict_list, 10)
    hobt_dicts = paginator.get_page(page)

    context = {'hobt_dicts': hobt_dicts, 'page': page, 'q': q}
    return render(request, 'hobt_dict/hobt_dict.html', context)

HoBT/hobt_dict/views/adsp_dict_views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.db.models import Q
from ..models import HobtDict


# ADsP 문제만 보여주는 뷰 함수
def adsp_dict(request):
    q = request.GET.get('q', '')  # 검색어
    adsp_dict_list = HobtDict.objects.filter(subject='ADsP').order_by('-qid')

    if q:
        adsp_dict_list = adsp_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q) | Q(qid__icontains=q)
            | Q(small_category__icontains=q) | Q(big_category__icontains=q) | Q(appearance_date__icontains=q)
        ).distinct()

    paginator = Paginator(adsp_dict_list, 10)
    page = request.GET.get('page', 1)
    adsp_dicts = paginator.get_page(page)

    start_index = max(1, adsp_dicts.number - 5)
    end_index = min(start_index + 10, adsp_dicts.paginator.num_pages + 1)
    page_range = range(start_index, end_index)

    context = {'adsp_dicts': adsp_dicts, 'page': page, 'q': q, 'page_range': page_range}
    return render(request, 'hobt_dict/ADsP_dict.html', context)


def adsp_search(request):
    """
    문제 검색 기능
    """
    q = request.GET.get('q', '')  # 검색어
    page = request.GET.get('page', '1')  # 페이지

    adsp_dict_list = HobtDict.objects.filter(subject='ADsP').order_by('-qid')
    if q:
        adsp_dict_list = adsp_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q)| Q(qid__icontains=q)
            | Q(small_category__icontains=q)| Q(big_category__icontains=q)| Q(appearance_date__icontains=q) |
            Q(subject__icontains=q)
        ).distinct()

    paginator = Paginator(adsp_dict_list, 10)
    adsp_dicts = paginator.get_page(page)

    start_index = max(1, adsp_dicts.number - 5)
    end_index = min(start_index + 10, adsp_dicts.paginator.num_pages + 1)
    page_range = range(start_index, end_index)

    context = {'adsp_dicts': adsp_dicts, 'page': page, 'q': q, 'page_range': page_range}
    return render(request, 'hobt_dict/ADsP_dict.html', context)

HoBT/hobt_dict/views/cs_dict_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required

from ..models import HobtDict
from ..forms import HobtDictForm


# 정보처리기사 문제만 보여주는 뷰 함수
def cs_dict(request):
    q = request.GET.get('q', '')  # 검색어
    cs_dict_list = HobtDict.objects.filter(subject='정보처리기사').order_by('-qid')

    if q:
        cs_dict_list = cs_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q) | Q(qid__icontains=q)
            | Q(small_category__icontains=q) | Q(big_category__icontains=q) | Q(appearance_date__icontains=q)
        ).distinct()

    paginator = Paginator(cs_dict_list, 10)
    page = request.GET.get('page', 1)
    cs_dicts = paginator.get_page(page)

    start_index = max(1, cs_dicts.number - 5)
    end_index = min(start_index + 10, cs_dicts.paginator.num_pages + 1)
    page_range = range(start_index, end_index)

    context = {'cs_dicts': cs_dicts, 'page': page, 'q': q, 'page_range': page_range}
    return render(request, 'hobt_dict/CS_dict.html', context)


def cs_search(request):
    """
    문제 검색 기능
    """
    q = request.GET.get('q', '')  # 검색어
    page = request.GET.get('page', '1')  # 페이지

    cs_dict_list = HobtDict.objects.filter(subject='정보처리기사').order_by('-qid')
    if q:
        cs_dict_list = cs_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q)| Q(qid__icontains=q)
            | Q(small_category__icontains=q)| Q(big_category__icontains=q)| Q(appearance_date__icontains=q) |
            Q(subject__icontains=q)
        ).distinct()

    paginator = Paginator(cs_dict_list, 10)
    cs_dicts = paginator.get_page(page)

    start_index = max(1, cs_dicts.number - 5)
    end_index = min(start_index + 10, cs_dicts.paginator.num_pages + 1)
    page_range = range(start_index, end_index)

    context = {'cs_dicts': cs_dicts, 'page': page, 'q': q, 'page_range': page_range}
    return render(request, 'hobt_dict/CS_dict.html', context)

HoBT/hobt_dict/views/hobt_dict_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required

from ..models import HobtDict
from ..forms import HobtDictForm


def hobt_dict(request):
    """
    문제 사전 게시판 메인 페이지
    """
    # 페이지네이션 기능 추가
    q = request.GET.get('q', '')  # 검색어
    page = request.GET.get('page', '1')  # 페이지

    hobt_dict_list = HobtDict.objects.order_by('-qid')
    if q:
        hobt_dict_list = hobt_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q) | Q(qid__icontains=q)
            | Q(small_category__icontains=q) | Q(big_category__icontains=q) | Q(appearance_date__icontains=q) |
            Q(subject__icontains=q)
        ).distinct()

    paginator = Paginator(hobt_dict_list, 10)
    hobt_dicts = paginator.get_page(page)

    start_index = max(1, hobt_dicts.number - 5)
    end_index = min(start_index + 10, hobt_dicts.paginator.num_pages + 1)
    page_range = range(start_index, end_index)

    context = {'hobt_dicts': hobt_dicts, 'page': page, 'q': q, 'page_range': page_range}
    return render(request, 'hobt_dict/hobt_dict.html', context)

# 현재는 사용하지 않는기능
# class HobtDictCreateView(View):
#     """
#     문제 등록
#     """
#     def get(self, request):
#         form = HobtDictForm()
#         return render(request, 'hobt_dict/hobt_dict_form.html', {'form': form})
#
#     def post(self, request):
#         form = HobtDictForm(request.POST)
#         if form.is_valid():
#             hobt_dict = form.save(commit=False)
#             hobt_dict.author = request.user
#             hobt_dict.save()
#             messages.success(request, '문제가 등록되었습니다.')
#             return redirect(hobt_dict)
#         return render(request, 'hobt_dict/hobt_dict_form.html', {'form': form})


@staff_member_required
def hobt_dict_modify(request, pk):
    """
    문제 수정
    """
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    # if request.user != hobt_dict.author:
    #     messages.error(request, '수정권한이 없습니다')
    #     return redirect('hobt_dict:hobt_dict_detail', pk=hobt_dict.pk)
    # 접근 자체를 관리자만 접근 할 수 있도록 작성해서 주석처리
    if request.method == 'POST':
        form = HobtDictForm(request.POST, instance=hobt_dict)
        if form.is_valid():
            hobt_dict = form.save(commit=False)
            hobt_dict.author = request.user
            hobt_dict.save()
            form.save_m2m()  # ManyToManyField를 저장하는 데 필요
            messages.success(request, '문제가 수정되었습니다')
            return redirect(hobt_dict)
    else:
        form = HobtDictForm(instance=hobt_dict)
    context = {
        'form': form,
        'qid': hobt_dict.qid,
    }
    return render(request, 'hobt_dict/hobt_dict_modify.html', context)


# @login_required(login_url='common:login')
# def hobt_dict_delete(request, pk):
#     """
#     문제 삭제
#     """
#     hobt_dict = get_object_or_404(HobtDict, pk=pk)
#     if request.user != hobt_dict.author:
#         messages.error(request, '삭제권한이 없습니다')
#     else:
#         hobt_dict.delete()
#         messages.success(request, '문제가 삭제되었습니다.')
#         return redirect('hobt_dict:hobt_dict')


@login_required(login_url='common:login')
@require_POST
def hobt_dict_like(request, pk):
    """
    문제 추천
    """
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    if hobt_dict.like.filter(id=request.user.id).exists():
        # 이미 추천한 경우
        hobt_dict.like.remove(request.user)
        message = '추천을 취소했습니다.'
    else:
        # 추천하지 않은 경우
        hobt_dict.like.add(request.user)
        message = '문제를 추천했습니다.'
    context = {'like_count': hobt_dict.like.count(), 'message': message}
    return JsonResponse(context)


def hobt_dict_detail(request, pk):
    hobt_dict = get_object_or_404(HobtDict, pk=pk)
    context = {'hobt_dict': hobt_dict}
    return render(request, 'hobt_dict/detail.html', context)


def hobt_search(request):
    """
    문제 검색 기능
    """
    q = request.GET.get('q', '')  # 검색어
    page = request.GET.get('page', '1')  # 페이지

    hobt_dict_list = HobtDict.objects.order_by('-qid')
    if q:
        hobt_dict_list = hobt_dict_list.filter(
            Q(answer__icontains=q) | Q(similar_answer__icontains=q) | Q(content__icontains=q)| Q(qid__icontains=q)
            | Q(small_category__icontains=q)| Q(big_category__icontains=q)| Q(appearance_date__icontains=q) |
            Q(subject__icontains=q)
        ).distinct()

    paginator = Paginator(hobt_dict_list, 10)
    hobt_dicts = paginator.get_page(page)

    start_index = max(1, hobt_dicts.number - 5)
    end_index = min(start_index + 10, hobt_dicts.paginator.num_pages + 1)
    page_range = range(start_index, end_index)

    context = {'hobt_dicts': hobt_dicts, 'page': page, 'q': q, 'page_range': page_range}
    return render(request, 'hobt_dict/hobt_dict.html', context)

HoBT/templates/hobt_dict/add_problem.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'hobt_dict.css' %}">
  <div class="content-container">
    <div class="container mt-3" style="max-width: 1000px; width: 100%;">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title mb-0">문제 입력</h3>
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                    <div class="form-group-inline">
                        <div class="form-group-big">
                          <label for="appearance_date">과목:</label>
                          {{ form.subject }}
                        </div>
                    </div>
                    <div class="form-group-inline">
                        <div class="form-group-mini">
                          <label for="answer">정답:</label>
                          <input type="text" class="form-control" id="answer" name="answer" required>
                        </div>
                        <div class="form-group-mini">
                          <label for="similar_answer">유사 답안:</label>
                          <input class="form-control" id="similar_answer" name="similar_answer" required>
                        </div>
                    </div>
                    <div class="form-group-inline">
                        <div class="form-group-big">
                          <label for="content">문제 내용:</label>
                          <textarea class="form-control" id="content" name="content" required></textarea>
                        </div>
                    </div>
                    <div class="form-group-inline">
                        <div class="form-group-big">
                          <label for="appearance_date">출제 유형:</label>
                          {{ form.appearance_date }}
                        </div>
                    </div>
                    <div class="form-group-inline">
                        <div class="form-group-mini">
                          <label for="small_category">소분류:</label>
                          <input type="text" class="form-control" id="small_category" name="small_category" required>
                        </div>
                        <div class="form-group-mini">
                          <label for="big_category">대분류:</label>
                          {{ form.big_category }}
                        </div>
                    </div>
                    <div class="form-group-inline">
                        <div class="form-group-big">
                          <label for="note">비고:</label>
                          <textarea class="form-control" id="note" name="note"></textarea>
                        </div>
                    </div>
                <div class="btn-group my-3" role="group">
                  <button type="submit" formaction="{% url 'hobt_dict:add_problem' %}" class="btn btn-primary mr-3">문제 추가</button>
                  <a href="{% url 'hobt_dict:problem_list' %}" class="btn btn-danger">문제 리스트</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

HoBT/templates/hobt_dict/hobt_dict_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h2>문제 등록</h2>
        <form method="post">
          {% csrf_token %}
          {% include 'hobt_dict/form.html' %}
          <button type="submit" class="btn btn-primary">저장</button>
          <a href="{% url 'hobt_dict:hobt_dict' %}" class="btn btn-secondary">취소</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

HoBT/templates/hobt_dict/problem_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container my-5">
    <h2 class="mb-4">
      <label>
        {% if request.user.is_staff%}
        <input type="checkbox" id="select-all-checkbox">관리자 문제 리스트
        {% else %}
        <input type="checkbox" id="select-all-checkbox">사용자 문제 리스트
        {% endif %}
      </label>
    </h2>
    <form method="post" action="{% url 'hobt_dict:add_selected_problems' %}">
      {% csrf_token %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>문제 번호</th>
            <th>문제 내용</th>
            <th>정답</th>
            <th>유사 답안</th>
            <th>출제 유형</th>
            <th>소분류</th>
            <th>대분류</th>
            <th>비고</th>
          </tr>
        </thead>
        <tbody>
          {% for problem in problems %}
              {% if request.user.id == problem.author_id or request.user.is_staff%}
                  <tr>
                    <td>
                      <div class="form-check">
                          <label>
                              <input class="form-check-input" type="checkbox" name="selected_problems" value="{{ problem.qid }}">
                          </label>
                          <label class="form-check-label" for="selected_problems">
                          {{ problem.qid }}
                        </label>
                      </div>
                    </td>
                    <td>{{ problem.content }}</td>
                    <td>{{ problem.answer }}</td>
                    <td>{{ problem.similar_answer }}</td>
                    <td>{{ problem.appearance_date }}</td>
                    <td>{{ problem.small_category }}</td>
                    <td>{{ problem.big_category }}</td>
                    <td>{{ problem.note }}</td>
                  </tr>
              {% endif %}
          {% endfor %}
        </tbody>
      </table>
      <div class="d-flex justify-content-center gap-3 mb-3">
        <a href="{% url 'hobt_dict:add_problem' %}" class="btn btn-secondary">문제 출제하기</a>
        <a href="{% url 'hobt:index' %}" class="btn btn-secondary">메인으로</a>
        <!-- 선택한 항목 삭제 버튼 -->
        <button type="button" id="delete-selected-problems-btn" class="btn btn-danger">선택한 항목 삭제</button>
      </div>
      <!-- 최종 제출 버튼 -->
{#      <div class="d-flex justify-content-center">#}
{#        {% if user.is_staff %}#}
{#        <form method="post" action="{% url 'hobt_dict:add_selected_problems' %}">#}
{#          {% csrf_token %}#}
{#          <button type="submit" class="btn btn-success">최종 제출</button>#}
{#        </form>#}
{#        {% endif %}#}
{#      </div>#}
    </form>
  </div>

  <script>
    // 전체 선택 체크박스 요소
    const selectAllCheckbox = document.querySelector('#select-all-checkbox');

    // 선택된 문제들의 체크박스 요소들
    const selectedCheckboxes = document.querySelectorAll('input[name="selected_problems"]');

    // 전체 선택 체크박스를 클릭했을 때, 선택된 문제들의 체크박스 요소들도 전체 선택/해제
    selectAllCheckbox.addEventListener('click', () => {
      for (let i = 0; i < selectedCheckboxes.length; i++) {
        selectedCheckboxes[i].checked = selectAllCheckbox.checked;
      }
    });

    // 선택한 항목 삭제 버튼 요소
    const deleteSelectedProblemsBtn = document.querySelector('#delete-selected-problems-btn');

    // 선택한 항목들을 삭제하는 함수
    function deleteSelectedProblems() {
      // 선택한 문제들의 체크박스 요소들
      const selectedCheckboxes = document.querySelectorAll('input[name="selected_problems"]:checked');
      // 선택한 문제들의 id 목록
      const selectedProblemIds = Array.from(selectedCheckboxes).map(checkbox => checkbox.value);

      if (selectedProblemIds.length > 0) {
        // 서버에 선택한 문제들을 삭제하는 요청 보내기
        fetch('{% url "hobt_dict:delete_selected_problems" %}', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify({
            selected_problem_ids: selectedProblemIds
          })
        })
        .then(response => {
          if (response.ok) {
            // 선택한 문제들이 성공적으로 삭제됐을 때, 화면에서 삭제하기
            selectedCheckboxes.forEach(checkbox => {
              checkbox.closest('tr').remove();
            });
            alert('선택한 항목이 삭제됐습니다.');
          } else {
            alert('문제 삭제에 실패했습니다.');
          }
        })
        .catch(error => {
          console.error(error);
          alert('문제 삭제에 실패했습니다.');
        });
      } else {
        alert('삭제할 항목을 선택해주세요.');
      }
    }

    // "선택한 항목 삭제" 버튼을 클릭했을 때, 선택한 항목들을 삭제하는 함수 실행
    deleteSelectedProblemsBtn.addEventListener('click', deleteSelectedProblems);

    // 최종 제출 버튼 요소
    const addSelectedProblemsBtn = document.querySelector('#add-selected-problems-btn');

    // 선택한 항목을 추가하는 함수
    function addSelectedProblems() {
    // 선택한 문제들의 체크박스 요소들
      const selectedCheckboxes = document.querySelectorAll('input[name="selected_problems"]:checked');
      // 선택한 문제들의 qid 목록
      const selectedProblemQids = Array.from(selectedCheckboxes).map(checkbox => checkbox.value);

      if (selectedProblemQids.length > 0) {
      // 서버에 선택한 문제들을 추가하는 요청 보내기
        fetch('{% url "hobt_dict:add_selected_problems" %}', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify({
            selected_problem_qids: selectedProblemQids
          })
        })
        .then(response => {
          if (response.ok) {
            alert('선택한 항목이 추가됐습니다.');
            window.location.reload();  // 페이지 새로고침
          } else {
            alert('문제 추가에 실패했습니다.');
          }
        })
        .catch(error => {
          console.error(error);
          alert('문제 추가에 실패했습니다.');
        });
      } else {
        alert('추가할 항목을 선택해주세요.');
      }
    }
    // "최종 제출" 버튼을 클릭했을 때, 선택한 항목을 추가하는 함수 실행
    addSelectedProblemsBtn.addEventListener('click', addSelectedProblems);
  </script>
{% endblock %}