HoBT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from hobt import views # pybo 디렉토리에 있는 views를 가져오기

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hobt/', include('hobt.urls')), # views의 index를 만들기
    path('common/', include('common.urls')),
    path('exam/', include('exam.urls')),
    path('', views.index, name="index"),
    path('hobt_dict/', include('hobt_dict.urls'))
]

HoBT/exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exam_judge/', views.exam_judge, name='exam_judge'),
    path('exam/', views.exam, name='exam'),
    path('exam_result/', views.exam_result, name='exam_result'),
    path('exam_select/', views.exam_select, name='exam_select')
]

HoBT/hobt/urls.py
from django.urls import path
from . import views

app_name = 'hobt'

urlpatterns = [
    # localhost:8000/hobt 주소의 루트를 의미함
    path('', views.index, name='index'),
    
    # 게시글 제목의 a 태그 href 속성에 해당하는 동적 URL 매핑
    path('<int:question_id>/', views.detail, name='detail'),
    
    # 답변 등록에 대한 URL 매핑
    path('answer/create/<int:question_id>/', views.answer_create, name="answer_create"),

    # 질문 등록에 대한 URL 매핑
    path("question/create/", views.question_create, name='question_create'),

    # 게시판 페이지에 대한 URL 매핑
    path('question/', views.question, name='question'),
    # 질문 수정에 대한 URL 매핑
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제에 대한 URL 매핑
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 수정에 대한 URL 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    # 답변 삭제에 대한 URL 매핑
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    # 질문 추천 URL 매핑
    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    # 답변 추천 URL 매핑
    path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
]

HoBT/hobt_dict/urls.py
from django.urls import path
from . import views

app_name = 'hobt_dict'
urlpatterns = [
    path('', views.hobt_dict, name='hobt_dict'), # 문제 사전 게시판 메인 페이지
    # path('create/', views.HobtDictCreateView.as_view(), name='hobt_dict_create'), # 문제 등록 현재는 사용하지 않는기능
    path('<int:pk>/modify/', views.hobt_dict_modify, name='hobt_dict_modify'), # 문제 수정
    # path('<int:pk>/delete/', views.hobt_dict_delete, name='hobt_dict_delete'), # 문제 삭제
    path('like/<int:pk>/\\Z', views.hobt_dict_like, name='hobt_dict_like'), # 문제 추천
    path('<int:pk>/', views.hobt_dict_detail, name='hobt_dict_detail'), # 문제 상세보기
    path('hobt_search/', views.hobt_search, name='hobt_search'), # 검색기능
    path('cs_search/', views.cs_search, name='cs_search'), # 검색기능
    path('adsp_search/', views.adsp_search, name='adsp_search'), # 검색기능
    path('add_problem/', views.add_problem, name='add_problem'), # 사용자가 문제를 추가
    path('problem_list/', views.show_problems, name='problem_list'), # 사용자 및 관리자가 추가한 문제 검토 리스트
    path('add_selected_problems/', views.add_selected_problems, name='add_selected_problems'),
    path('delete_selected_problems/', views.delete_selected_problems, name='delete_selected_problems'), # 체크박스 선택 항목 삭제
    path('cs_dict/', views.cs_dict, name='cs_dict'),
    path('adsp_dict/', views.adsp_dict, name='adsp_dict'),
]

HoBT/hobt/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# Models의 Model이란 클래스 상속
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200) # models에서 문자열 필드(200바이트까지 제한)
    content = models.TextField() # 문자열 제한이 없는 데이터 타입
    create_date = models.DateTimeField() # 날짜와 시간
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete= models.CASCADE) # Question을 외래키로, 삭제시 참조되는 모든걸 삭제
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

HoBT/hobt/forms.py
from django import forms

from hobt.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

HoBT/hobt/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('hobt:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'hobt/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('hobt:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('hobt:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'hobt/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('hobt:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
        resolve_url('hobt:detail', question_id=answer.question.id), answer.id))

HoBT/hobt/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.core.paginator import Paginator
from django.db.models import Q


def index(request):
    return render(request, 'hobt/index.html')


def question(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'hobt/question_list.html', context)


def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'hobt/question_detail.html', context)

HoBT/hobt/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == "POST":  # Post 요청일때는 입력한 값들을 전달받아 DB에 저장
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect("hobt:question")
    else:  # Get 요청일때는 단순히 질문등록 페이지 요청
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'hobt/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('hobt:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('hobt:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'hobt/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('hobt:detail', question_id=question.id)
    question.delete()
    return redirect('hobt:question')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('hobt:detail', question_id=question.id)

HoBT/templates/hobt/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

HoBT/templates/hobt/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid" style="background-image: url('/static/bg.jpg'); background-size: cover; background-position: center center;">
  <div class="row justify-content-center align-items-center" style="height: 92.5vh;">
    <div class="col-md-6 text-center">
      <p class="mb-4" style="font-size: 0.9rem; line-height: 2; margin-top: -50px; color: white;">정보처리기사 실기 CBT, 일명 HoBT입니다!<br>지금 바로 풀어 보시고 자격증을 취득해보세요!</p>
      <h1 style="font-size: 6rem; font-family: Cambria, serif; color: white;">HoBT</h1>
      <div class="mt-auto d-flex flex-row justify-content-center">
          <a id="start-button" style="font-size: 1.5rem; margin-top: 250px; margin-right: 30px;" href="{% url 'exam:exam_select' %}" class="btn btn-lg btn-primary"
             >문제 풀기</a>
          {% if user.is_authenticated %}
          <a style="font-size: 1.5rem; margin-top: 250px;" href="{% url 'hobt_dict:add_problem' %}" class="btn btn-lg btn-success">문제 만들기</a>
          {% endif %}
      </div>
    </div>
  </div>
</div>
<script src="{% static 'index.js' %}"></script>
{% endblock %}

HoBT/templates/hobt/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'hobt:question_vote' question.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{% url 'hobt:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'hobt:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'hobt:answer_vote' answer.id  %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'hobt:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'hobt:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'hobt:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

HoBT/templates/hobt/question_form.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post">
{#        Django에서 form 태그내에서 action 속성을 사용하지 않으면, 기본 페이지 URL이 Default로 설정 #}
{#        <form method="post" action="{% url "hobt:question_create" %}">로 사용해도 되고, 안해도 무관 #}
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="subject" class="form-label">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                       value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea class="form-control" name="content"
                          id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">질문저장</button>
        </form>
    </div>
{% endblock %}

HoBT/templates/hobt/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'hobt:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="table-dark text-center">
                <th style="width:15%">번호</th>
                <th >제목</th>
                <th>글쓴이</th>
                <th style="width:25%">작성일</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                {#      번호 = 전체건수 - 시작인덱스 - 현재인덱스 +1 #}
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td style="font-size: 0.9rem" class="text-start">
                <a href="{% url 'hobt:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-0">
                    <sub>{{ question.answer_set.count }}</sub>
                </span>
                {% endif %}
            </td>
            <td style="font-size: 0.8rem">{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date|date:'Y/n/j H:i:s' }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
               href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}"
                   href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}"
                   href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'hobt:question' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    console.log(document.getElementById('kw').value);
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}