HoBT/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # Django에서 지원하는 views 라이브러리를 활용 (로그인, 로그아웃, 비밀번호 찾기&초기화 등)
    # pybo.urls에서 연결되는 views.py 파일의 함수를 만들 필요가 없음(Django가 알아서 다 처리)
    path('login/', auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.signup, name="signup"),
    path('withdrawal/', views.withdrawal, name='withdrawal'),
]

HoBT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from hobt import views # pybo 디렉토리에 있는 views를 가져오기

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hobt/', include('hobt.urls')), # views의 index를 만들기
    path('common/', include('common.urls')),
    path('exam/', include('exam.urls')),
    path('', views.index, name="index"),
    path('hobt_dict/', include('hobt_dict.urls'))
]

HoBT/exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exam_judge/', views.exam_judge, name='exam_judge'),
    path('exam/', views.exam, name='exam'),
    path('exam_result/', views.exam_result, name='exam_result'),
    path('exam_select/', views.exam_select, name='exam_select')
]

HoBT/hobt/urls.py
from django.urls import path
from . import views

app_name = 'hobt'

urlpatterns = [
    # localhost:8000/hobt 주소의 루트를 의미함
    path('', views.index, name='index'),
    
    # 게시글 제목의 a 태그 href 속성에 해당하는 동적 URL 매핑
    path('<int:question_id>/', views.detail, name='detail'),
    
    # 답변 등록에 대한 URL 매핑
    path('answer/create/<int:question_id>/', views.answer_create, name="answer_create"),

    # 질문 등록에 대한 URL 매핑
    path("question/create/", views.question_create, name='question_create'),

    # 게시판 페이지에 대한 URL 매핑
    path('question/', views.question, name='question'),
    # 질문 수정에 대한 URL 매핑
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제에 대한 URL 매핑
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 수정에 대한 URL 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    # 답변 삭제에 대한 URL 매핑
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    # 질문 추천 URL 매핑
    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    # 답변 추천 URL 매핑
    path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
]

HoBT/hobt_dict/urls.py
from django.urls import path
from . import views

app_name = 'hobt_dict'
urlpatterns = [
    path('', views.hobt_dict, name='hobt_dict'), # 문제 사전 게시판 메인 페이지
    # path('create/', views.HobtDictCreateView.as_view(), name='hobt_dict_create'), # 문제 등록 현재는 사용하지 않는기능
    path('<int:pk>/modify/', views.hobt_dict_modify, name='hobt_dict_modify'), # 문제 수정
    # path('<int:pk>/delete/', views.hobt_dict_delete, name='hobt_dict_delete'), # 문제 삭제
    path('like/<int:pk>/\\Z', views.hobt_dict_like, name='hobt_dict_like'), # 문제 추천
    path('<int:pk>/', views.hobt_dict_detail, name='hobt_dict_detail'), # 문제 상세보기
    path('hobt_search/', views.hobt_search, name='hobt_search'), # 검색기능
    path('cs_search/', views.cs_search, name='cs_search'), # 검색기능
    path('adsp_search/', views.adsp_search, name='adsp_search'), # 검색기능
    path('add_problem/', views.add_problem, name='add_problem'), # 사용자가 문제를 추가
    path('problem_list/', views.show_problems, name='problem_list'), # 사용자 및 관리자가 추가한 문제 검토 리스트
    path('add_selected_problems/', views.add_selected_problems, name='add_selected_problems'),
    path('delete_selected_problems/', views.delete_selected_problems, name='delete_selected_problems'), # 체크박스 선택 항목 삭제
    path('cs_dict/', views.cs_dict, name='cs_dict'),
    path('adsp_dict/', views.adsp_dict, name='adsp_dict'),
]

HoBT/hobt/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.core.paginator import Paginator
from django.db.models import Q


def index(request):
    return render(request, 'hobt/index.html')


def question(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'hobt/question_list.html', context)


def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'hobt/question_detail.html', context)

HoBT/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
{#    <link rel="stylesheet" href="{% static 'darkly.min.css' %}">#}
    <title>최강기출 HoBT!</title>
</head>
<body>
{% include "layout.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.js' %}"></script>
<script src="{% static 'bootstrap.bundle.js' %}"></script>
<script src="{% static 'bootstrap.esm.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

HoBT/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} {#필드 오류를 출력한다.#}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} {# 넌필드 오류를 출력한다. #}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

HoBT/templates/layout.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'layout.css' %}">
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">HoBT</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url "common:logout" %}">{{ user.username }}로그아웃</a>
                    {% else %}
                    <a class="nav-link" href="{% url "common:login" %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url "common:withdrawal" %}">회원탈퇴</a>
                    {% else %}
                    <a class="nav-link" href="{% url "common:signup" %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" href="{% url 'hobt:question' %}">질문 게시판</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        문제 사전
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'hobt_dict:hobt_dict' %}">종합 문제 사전</a></li>
                        <li><a class="dropdown-item" href="{% url 'hobt_dict:cs_dict' %}">정보처리기사 문제 사전</a></li>
                        <li><a class="dropdown-item" href="{% url 'hobt_dict:adsp_dict' %}">ADsP 문제 사전</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>