HoBT/config/urls.py
from django.contrib import admin
from django.urls import path, include
from hobt import views # pybo 디렉토리에 있는 views를 가져오기

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hobt/', include('hobt.urls')), # views의 index를 만들기
    path('common/', include('common.urls')),
    path('exam/', include('exam.urls')),
    path('', views.index, name="index"),
    path('hobt_dict/', include('hobt_dict.urls'))
]

HoBT/exam/urls.py
from django.urls import path
from . import views

app_name = 'exam'

urlpatterns = [
    path('exam_judge/', views.exam_judge, name='exam_judge'),
    path('exam/', views.exam, name='exam'),
    path('exam_result/', views.exam_result, name='exam_result'),
    path('exam_select/', views.exam_select, name='exam_select')
]

HoBT/hobt/urls.py
from django.urls import path
from . import views

app_name = 'hobt'

urlpatterns = [
    # localhost:8000/hobt 주소의 루트를 의미함
    path('', views.index, name='index'),
    
    # 게시글 제목의 a 태그 href 속성에 해당하는 동적 URL 매핑
    path('<int:question_id>/', views.detail, name='detail'),
    
    # 답변 등록에 대한 URL 매핑
    path('answer/create/<int:question_id>/', views.answer_create, name="answer_create"),

    # 질문 등록에 대한 URL 매핑
    path("question/create/", views.question_create, name='question_create'),

    # 게시판 페이지에 대한 URL 매핑
    path('question/', views.question, name='question'),
    # 질문 수정에 대한 URL 매핑
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제에 대한 URL 매핑
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    # 답변 수정에 대한 URL 매핑
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    # 답변 삭제에 대한 URL 매핑
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    # 질문 추천 URL 매핑
    path('question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    # 답변 추천 URL 매핑
    path('answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),
]

HoBT/hobt_dict/urls.py
from django.urls import path
from . import views

app_name = 'hobt_dict'
urlpatterns = [
    path('', views.hobt_dict, name='hobt_dict'), # 문제 사전 게시판 메인 페이지
    # path('create/', views.HobtDictCreateView.as_view(), name='hobt_dict_create'), # 문제 등록 현재는 사용하지 않는기능
    path('<int:pk>/modify/', views.hobt_dict_modify, name='hobt_dict_modify'), # 문제 수정
    # path('<int:pk>/delete/', views.hobt_dict_delete, name='hobt_dict_delete'), # 문제 삭제
    path('like/<int:pk>/\\Z', views.hobt_dict_like, name='hobt_dict_like'), # 문제 추천
    path('<int:pk>/', views.hobt_dict_detail, name='hobt_dict_detail'), # 문제 상세보기
    path('hobt_search/', views.hobt_search, name='hobt_search'), # 검색기능
    path('cs_search/', views.cs_search, name='cs_search'), # 검색기능
    path('adsp_search/', views.adsp_search, name='adsp_search'), # 검색기능
    path('add_problem/', views.add_problem, name='add_problem'), # 사용자가 문제를 추가
    path('problem_list/', views.show_problems, name='problem_list'), # 사용자 및 관리자가 추가한 문제 검토 리스트
    path('add_selected_problems/', views.add_selected_problems, name='add_selected_problems'),
    path('delete_selected_problems/', views.delete_selected_problems, name='delete_selected_problems'), # 체크박스 선택 항목 삭제
    path('cs_dict/', views.cs_dict, name='cs_dict'),
    path('adsp_dict/', views.adsp_dict, name='adsp_dict'),
]

HoBT/exam/models.py
from django.db import models


class Hobt1(models.Model):
    qid = models.IntegerField(primary_key=True)
    answer = models.TextField()
    similar_answer = models.TextField()
    content = models.TextField()
    appearance_date = models.TextField()
    small_category = models.TextField()
    big_category = models.TextField()
    note = models.TextField()

    class Meta:
        db_table = 'hobt_1'
        ordering = ['qid']

HoBT/exam/views.py
import pandas as pd
import re
from django.shortcuts import render, redirect, get_object_or_404
from .models import Hobt1
from hobt_dict.models import HobtDict
from .utils import wrap_text
from django.http import HttpResponse

def exam(request):
    hobt_1_list = Hobt1.objects.all()
    # for problem in hobt_1_list:
    #     problem.content = problem.content.replace('.', '.<br>').replace('?', '?<br>')
    # 세션에서 data_list를 가져옴
    data_list = request.session.get('data_list', [])
    return render(request, 'exam/exam.html', {'data_list': data_list})


def exam_judge(request):
    problem_id = request.GET.get('problem_id', '')
    problem = HobtDict.objects.get(qid=problem_id)
    first_answer = request.GET.get('answer', '')
    answer = problem.answer
    similar_answer = problem.similar_answer
    is_correct = first_answer.strip() == answer.strip()
    context = {
        'problem_id': problem_id,
        'first_answer': first_answer,
        'answer': answer,
        'similar_answer': similar_answer,
        'is_correct': is_correct,
    }
    return render(request, 'exam/exam_judge.html', context)

def exam_result(request):
    return render(request, 'exam/exam_result.html')


def exam_select(request):

    qs = HobtDict.objects.filter(subject='정보처리기사').values()
    for problem in qs:
        problem['content'] = re.sub(r'(\.|\?)\s', r'\1<br>', problem['content'])
    data = pd.DataFrame(qs)
    random_data = data.sample(n=20, replace=False).reset_index(drop=True)

    # 데이터 프레임을 딕셔너리 목록으로 변환
    data_list = random_data.to_dict('records')

    for item in data_list:
        for key, value in item.items():
            if isinstance(value, pd.Timestamp):
                # Timestamp 객체를 문자열로 변환
                item[key] = value.strftime('%Y-%m-%d %H:%M:%S')
            elif pd.isna(value):
                # NaTType 객체를 빈 문자열로 변환
                item[key] = ''



    # data_list를 세션 변수로 저장
    request.session['data_list'] = data_list

    context = {'data_list': data_list}
    return render(request, 'exam/exam_select.html', context)

HoBT/templates/exam/add_problem.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
  <h2 class="mb-4">문제 입력</h2>
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="qid">문제 번호:</label>
          <input type="number" class="form-control" id="qid" name="qid" required>
        </div>
        <div class="form-group">
          <label for="answer">문제 정답:</label>
          <input type="text" class="form-control" id="answer" name="answer" required>
        </div>
        <div class="form-group">
          <label for="similar_answer">문제 유사 정답:</label>
          <textarea class="form-control" id="similar_answer" name="similar_answer"></textarea>
        </div>
        <div class="form-group">
          <label for="content">문제 내용:</label>
          <textarea class="form-control" id="content" name="content" required></textarea>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="appearance_date">출제 연도:</label>
          <input type="text" class="form-control" id="appearance_date" name="appearance_date" required>
        </div>
        <div class="form-group">
          <label for="small_category">문제 소 분류:</label>
          <input type="text" class="form-control" id="small_category" name="small_category" required>
        </div>
        <div class="form-group">
          <label for="big_category">문제 대 분류:</label>
          <input type="text" class="form-control" id="big_category" name="big_category" required>
        </div>
        <div class="form-group">
          <label for="note">비고:</label>
          <textarea class="form-control" id="note" name="note"></textarea>
        </div>
      </div>
    </div>
    <div class="btn-group my-3" role="group">
      <button type="submit" formaction="{% url 'exam:add_problem' %}" class="btn btn-primary mr-3">문제 추가</button>
      <a href="{% url 'exam:problem_list' %}" class="btn btn-danger">문제 리스트</a>
    </div>
  </form>
</div>
{% endblock %}

HoBT/templates/exam/exam.html
{% extends 'base.html' %}

{% block content %}
  <style>
  .btn {
  width: 120px;
  height: 50px;
  font-size: 20px;
  }
  body {
    background-color: #f2f2f2;
  }
</style>
  <div class="container my-5" style="font-size: 120%;">
    <div class="row">
      <div class="d-flex justify-content-between">
        <h2 class="mr-auto">문제 리스트</h2>
        <form action="{% url 'exam:exam_result' %}" method="get">
          <button tabindex="3" type="submit" class="btn btn-primary ml-2">채점하기</button>
        </form>
      </div>
      {% for row in data_list %}
         <div class="col-12 my-3 problem-card" id="{{ forloop.counter }}">
          <div class="card" style="border: 1px solid black;">
            <div class="card-body">
              <h4 class="card-title">{{ forloop.counter }}번 문제</h4>
              <p class="card-text">출제연도 : {{ row.appearance_date }}<br>
              문제대분류 : {{ row.big_category }}<br>
              문제소분류 : {{ row.small_category }}<br></p><br>
              <p class="card-text">문제 : {{ row.content|safe }}  </p><br>
              <form action="{% url 'exam:exam_judge' %}" method="get">
                  <label for="answer{{ row.qid }}">정답 :</label><br>
                <div class="form-group d-flex flex-row align-items-center my-0 gap-2">
                  <div class="d-flex flex-column justify-content-center" style="width: 100%">
                    <input style="height: 50px; font-size: 110%; border: 1px solid black;" tabindex="1" type="text" class="form-control ml-2" id="answer{{ row.qid }}" name="answer">
                  <div class="text-center">
                    <button tabindex="2" type="submit" class="btn btn-primary mt-2">제출</button>
                  </div>
                    <input type="hidden" name="problem_id" value="{{ row.qid }}">
                  </div>
                </div>
              </form>
              <div class="mt-3">
                <span id="answer-display{{ row.qid }}"></span>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      <div class="col-12 mt-3 d-flex justify-content-center">
        {% for problem in hobt_1 %}
          <button class="btn btn-primary mx-2{% if problem.qid == button_num %} active{% endif %}" onclick="showProblem('{{ problem.qid }}'); setRedirectUrl('{{ problem.qid }}'); setActiveButton('{{ problem.qid }}')">
            <span class="btn-number{% if problem.qid == button_num %} active{% endif %}" {% if problem.qid == button_num %} autofocus {% endif %}>{{ problem.qid }}</span>
          </button>
        {% endfor %}
      </div>
    </div>
  </div>
  <script>
  // 브라우저 뒤로가기 버튼 방지
  window.history.pushState(null, null, window.location.href);
  window.onpopstate = function() {
    window.history.go(1);
  };

  var redirectUrl = '{% url "exam:exam" %}';
  var button_num = localStorage.getItem('exam_number');

  function setRedirectUrl(problemId) {
    redirectUrl = '{% url "exam:exam" %}?exam_number=' + problemId;
  }

  function showProblem(id) {
    var problemCards = document.getElementsByClassName('problem-card');
    for (var i = 0; i < problemCards.length; i++) {
      if (problemCards[i].getAttribute('id') == id) {
        problemCards[i].style.display = 'block';
        var answerInput = problemCards[i].querySelector('input[name="answer"]');
        answerInput.focus();
      } else {
        problemCards[i].style.display = 'none';
      }
    }
  }

  function setActiveButton(problemId) {
    button_num = problemId;
    var buttons = document.querySelectorAll('.btn-number');
    for (var i = 0; i < buttons.length; i++) {
      if (buttons[i].innerText == problemId) {
        buttons[i].parentNode.classList.add('active');
      } else {
        buttons[i].parentNode.classList.remove('active');
      }
    }
  }

  // 제출 버튼 클릭 이벤트 리스너 추가
  var submitButtons = document.getElementsByTagName('button');
  for (var i = 0; i < submitButtons.length; i++) {
    if (submitButtons[i].type == 'submit') {
      submitButtons[i].addEventListener('click', function() {
        // form submit 후 리다이렉트
        var problemId = this.parentNode.querySelector('input[name="problem_id"]').value;
        var answer = this.parentNode.querySelector('input[name="answer"]').value;
        var answerDisplay = this.parentNode.parentNode.querySelector('span[id="answer-display' + problemId + '"]');
        answerDisplay.innerText = '당신이 입력한 답 : ' + answer;
        this.parentNode.submit();
        window.location.href = redirectUrl;
      });
    }
  }

  // 문제 1을 보여주는 코드
  window.onload = function() {
    showProblem(localStorage.getItem('exam_number'));
    setActiveButton(localStorage.getItem('exam_number'));
  }
// p 요소의 innerHTML을 localStorage에서 가져온 값으로 설정
  document.getElementById('exam_number').innerHTML = localStorage.getItem('exam_number');


</script>
{% endblock %}

HoBT/templates/exam/exam_judge.html
{% extends 'base.html' %}

{% block content %}
<style>
  .btn {
  width: 120px;
  height: 50px;
  font-size: 20px;
  }
  body {
    background-color: #f2f2f2;
  }
  .form-group {
  text-align: center;
  overflow: auto; /* 추가 */
  }
</style>
<div class="container my-5">
    <div class="row">
      <div class="col-12 mb-3">
        <h2>문제 결과</h2>
      </div>
      <div class="col-12">
        <div class="row">
          <div class="col-12 col-md-4 mb-3">
            <div class="card text-center">
               <div class="card-body" style=" border-radius: 5px; background-color: lightyellow; font-size:140%;">
                <h4 class="card-title">작성 답안</h4><hr>
                {% if first_answer %}
                <p class="card-text">{{ first_answer }}</p>
                {% else %}
                <p class="card-text">없음</p>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="col-12 col-md-4 mb-3">
            <div class="card text-center border-{{ answer_status }}">
              <div class="card-body" style=" border-radius: 5px; background-color: lightyellow; font-size:140%;">
                <h4 class="card-title">실제 답안</h4><hr>
                <p class="card-text">{{ answer }}</p>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-4 mb-3">
            <div class="card text-center">
              <div class="card-body" style=" border-radius: 5px; background-color: lightyellow; font-size:140%;">
                <h4 class="card-title">유사 답안</h4><hr>
                <p class="card-text">{{ similar_answer }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 mt-2">
        <form id="judgement-form" action="{% url 'exam:exam' %}" method="get">
          <div class="form-group" style="text-align:center;">
            <label for="judgement" style="font-size:1.5rem;">당신이 입력한 답이 정답이라고 생각하시나요?</label>
            <p></p>
            <div>
              <button id="judgement-button-1" type="button" class="btn btn-success" onclick="setJudgementValue('1'); showCongratulation(); showSubmitButton();">정답 : 1</button>
              <button id="judgement-button-2" type="button" class="btn btn-danger" onclick="setJudgementValue('2'); showRegret(); showSubmitButton();">오답 : 2</button>
            </div>
          </div>
          <input type="hidden" id="judgement" name="judgement" required>
          <input type="hidden" name="exam_number" value="exam_number">
          <input id="submit-button" class="btn btn-primary mt-3" type="submit" value="제출" style="display: none; margin: auto;">
        </form>
       <div>
        <form id="result-form" action="{% url 'exam:exam_result' %}" method="get">
          <button tabindex="1" id="final-button" type="submit" class="btn btn-primary ml-2" style="display: none; margin: 0 auto; width: auto;">채점하기(tab을 눌러보세요!)</button>
        </form>
      </div>
      </div>
    </div>
  </div>
 <div class="container" style="max-width: 1300px; font-size: 140%; text-align:center;">
  <div id="congratulation-message" class="card d-none bg-success text-white">
    <div class="card-body text-left">
      <script>
        score = localStorage.setItem('score', {{ score }} + 5);
      </script>
      <h4 class="card-title">축하합니다!</h4>
        <p class="card-text"><p id="correct_answer"></p><p id="correct_exam_number"></p></p>
    </div>
  </div>

  <div id="regret-message" class="card d-none bg-danger text-white">
    <div class="card-body text-left">
      <h4 class="card-title">유감입니다!</h4>
        <p class="card-text"><p id="wrong_answer"></p><p id="wrong_exam_number"></p></p>
    </div>
  </div>
</div>

  <script>
  let is_correct = 0;
  let is_enter_pressed = false;

    function setJudgementValue(value) {
  if (!document.getElementById('judgement-button-1').classList.contains('d-none') && !document.getElementById('judgement-button-2').classList.contains('d-none')) {
    is_correct = parseInt(value);
    document.getElementById('judgement').value = value;
  }
}

   function showCongratulation() {
  if (document.getElementById('congratulation-message').classList.contains('d-none')) {
    document.getElementById('congratulation-message').classList.remove('d-none');
    document.getElementById('regret-message').classList.add('d-none');
    document.getElementById('judgement-button-1').classList.add('d-none');
    document.getElementById('judgement-button-2').classList.remove('d-none');
    total_score = parseInt(localStorage.getItem('total_score'));
    if (total_score < 100) {
      localStorage.setItem('total_score', total_score + 5);
    }
  }
  document.getElementById('judgement-button-2').classList.add('d-none');
}

function showRegret() {
  if (document.getElementById('regret-message').classList.contains('d-none')) {
    document.getElementById('regret-message').classList.remove('d-none');
    document.getElementById('congratulation-message').classList.add('d-none');
    document.getElementById('judgement-button-2').classList.add('d-none');
    document.getElementById('judgement-button-1').classList.remove('d-none');
  }
  document.getElementById('judgement-button-1').classList.add('d-none');
}

function showSubmitButton() {
    if (exam_number === 20) {
        document.getElementById('final-button').style.display = 'block';
    } else {
        document.getElementById('submit-button').style.display = 'block';
    }
};

document.addEventListener('keydown', function(event) {
  if (event.code === 'Digit1' && !document.getElementById('judgement-button-1').classList.contains('d-none')) {
    setJudgementValue('1');
    showCongratulation();
    showSubmitButton();
    document.getElementById('submit-button').focus();
    event.preventDefault();
  } else if (event.code === 'Digit2' && !document.getElementById('judgement-button-2').classList.contains('d-none')) {
    setJudgementValue('2');
    showRegret();
    showSubmitButton();
    document.getElementById('submit-button').focus();
    event.preventDefault();
  }
});

document.getElementById('judgement-button-1').addEventListener('click', function() {
  setJudgementValue('1');
  showCongratulation();
  showSubmitButton();
  document.getElementById('submit-button').focus();
  document.getElementById('judgement-button-2').classList.add('d-none');
  window.scrollTo(0,document.body.scrollHeight);
});

document.getElementById('judgement-button-2').addEventListener('click', function() {
  setJudgementValue('2');
  showRegret();
  showSubmitButton();
  document.getElementById('submit-button').focus();
  document.getElementById('judgement-button-1').classList.add('d-none');
  window.scrollTo(0,document.body.scrollHeight);
});

document.getElementById('submit-button').addEventListener('click', function() {
  // localStorage 값 증가
  if (is_enter_pressed == false) {
      if (exam_number < 20) {
          localStorage.setItem('exam_number', exam_number + 1);
      } else {
          localStorage.setItem('exam_number', 20);
      }
      if (is_correct == 1) {
          correct_answer = parseInt(localStorage.getItem('correct_answer'));
          localStorage.setItem('correct_answer', correct_answer + 1);
          is_enter_pressed = true;
      } else {
          is_enter_pressed = true;
      }
  }
});

    correct_answer = parseInt(localStorage.getItem('correct_answer'));
    exam_number = parseInt(localStorage.getItem('exam_number'));
    total_score = parseInt(localStorage.getItem('total_score'));
    document.getElementById('correct_answer').innerHTML = `현재 맞춘 문제 수는 ${correct_answer+1}개입니다.<br>다음 문제를 풀어보세요!`
    document.getElementById('wrong_answer').innerHTML = `현재 맞춘 문제 수는 ${correct_answer}개입니다.<br>다음 문제를 풀어보세요!`
    document.getElementById('wrong_exam_number').innerHTML = `남은 문항 수: ${20-exam_number}개`
    document.getElementById('correct_exam_number').innerHTML = `남은 문항 수: ${20-exam_number}개`

    window.history.pushState(null, null, window.location.href);
    window.onpopstate = function () {
      window.history.go(1);
    };
  </script>
{% endblock %}

HoBT/templates/exam/exam_result.html
{% extends 'base.html' %}

{% block content %}
  <style>
  body {
    background-color: #f2f2f2;
  }
  .btn {
  width: 120px;
  height: 50px;
  font-size: 20px;
  }
  body {
    background-color: #f2f2f2;
  }
</style>

<div class="card my-5">
  <div class="card-body">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8 text-center">
          <h2 class="mb-4"><br>당신의 점수는 <span id="total_score" class="text-primary">{{ total_score }}</span>점입니다!</h2><br>
          <h4 id="result_message" class="text-success font-weight-bold"></h4>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center my-3">
  <div class="col-md-4 mb-2 text-center">
    <button tabindex="1" class="btn btn-primary btn-block mx-2" onclick="restartExam()" autofocus>다시 풀기</button>
    <button tabindex="2" class="btn btn-danger btn-block mx-2" onclick="exitExam()">문제 선택</button>
  </div>
</div>


<script>
  function restartExam() {
    localStorage.setItem('exam_number', 1);
    localStorage.setItem('total_score', 0);
    localStorage.setItem('correct_answer', 0);
    window.location.href = "{% url 'exam:exam' %}";
  }

  function exitExam() {
    window.location.href = "{% url 'exam:exam_select' %}";
  }

  var total_score = localStorage.getItem('total_score');
  document.getElementById('total_score').innerHTML = total_score;

  var result_message = document.getElementById('result_message');

  if (total_score < 60) {
    result_message.innerHTML = '불합격입니다. 문제를 다시 풀어보세요!<br><br>';
    result_message.classList.add("text-danger");
  } else if (total_score < 70) {
    result_message.innerHTML = '합격입니다. 다시 풀어보세요! <br><br> 점수를 70점까지 올려보세요!<br><br>';
    result_message.classList.add("text-warning");
  } else {
    result_message.innerHTML = '축하합니다. 합격입니다! <br><br> 메인 메뉴로 돌아가서 새로운 문제를 풀어보세요!<br><br>';
    result_message.classList.add("text-success");
  }

  // 브라우저 뒤로가기 버튼 방지
  window.history.pushState(null, null, window.location.href);
  window.onpopstate = function() {
    window.history.go(1);
  };
</script>
{% endblock %}

HoBT/templates/exam/exam_select.html
{% extends "base.html" %}

{% block content %}
<style>
  .btn {
    width: 130px;
    height: 50px;
    font-size: 20px;
  }

  body {
    background-color: #f2f2f2;
    font-size: 1.2rem;
  }
</style>
  <div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card w-auto mx-auto">
        <div class="card-body text-center">
          <h1 class="display-4">문제 유형 선택</h1><br>
          <p>이 페이지부터는 뒤로가기 버튼을 사용하실 수 없습니다.<br>버튼을 이용해서 메인메뉴로 이동해주세요!</p>
          <br>
          <div class="d-flex justify-content-center mb-3 gap-2">
            <a tabindex="2" href="/" class="btn btn-danger btn-lg mr-2">메인메뉴</a>
            <form action="{% url 'exam:exam' %}" method="get">
              {% csrf_token %}
              <button tabindex="1" type="submit" class="btn btn-primary btn-lg mr-2"
                      onclick="localStorage.setItem('exam_number', 1), localStorage.setItem('total_score', 0),
             localStorage.setItem('correct_answer', 0)" autofocus>단답형</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  window.history.pushState(null, null, window.location.href);
  window.onpopstate = function () {
    window.history.go(1);
};
</script>
</script>
{% endblock %}

HoBT/templates/exam/problem_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container my-5">
    <h2 class="mb-4">
      <label>
        <input type="checkbox" id="select-all-checkbox">
        관리자 문제 리스트
      </label>
    </h2>
    <form method="post" action="{% url 'exam:add_selected_problems' %}">
      {% csrf_token %}
      <table class="table table-striped">
        <thead>
          <tr>
            <th>문제 번호</th>
            <th>문제 내용</th>
            <th>문제 정답</th>
            <th>문제 유사 정답</th>
            <th>출제 연도</th>
            <th>소 분류</th>
            <th>대 분류</th>
            <th>비고</th>
          </tr>
        </thead>
        <tbody>
          {% for problem in problems %}
          <tr>
            <td>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" name="selected_problems" value="{{ problem.qid }}">
                <label class="form-check-label" for="selected_problems">
                  {{ problem.qid }}
                </label>
              </div>
            </td>
            <td>{{ problem.content }}</td>
            <td>{{ problem.answer }}</td>
            <td>{{ problem.similar_answer }}</td>
            <td>{{ problem.appearance_date }}</td>
            <td>{{ problem.small_category }}</td>
            <td>{{ problem.big_category }}</td>
            <td>{{ problem.note }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <a href="{% url 'exam:add_problem' %}" class="btn btn-secondary">문제 출제하기</a>
        <a href="{% url 'hobt:index' %}" class="btn btn-secondary">메인으로</a>
      </div>
      <!-- 최종 제출 버튼 -->
      <div class="d-flex justify-content-center">
        <form method="post" action="{% url 'exam:add_selected_problems' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-success">최종 제출</button>
        </form>
      </div>
    </form>
  </div>

  <script>
    // 전체 선택 체크박스 요소
    const selectAllCheckbox = document.querySelector('#select-all-checkbox');

    // 선택된 문제들의 체크박스 요소들
    const selectedCheckboxes = document.querySelectorAll('input[name="selected_problems"]');

    // 전체 선택 체크박스를 클릭했을 때, 선택된 문제들의 체크박스 요소들도 전체 선택/해제
    selectAllCheckbox.addEventListener('click', () => {
      for (let i = 0; i < selectedCheckboxes.length; i++) {
        selectedCheckboxes[i].checked = selectAllCheckbox.checked;
      }
    });
  </script>
{% endblock %}

HoBT/templates/exam/result.html
{% extends 'base.html' %}

{% block content %}
  <div class="container my-5">
    <h2>결과</h2>
    <p>총 문제 수: {{ total }}</p>
    <p>맞은 문제 수: {{ correct_answers }}</p>
    <p>틀린 문제 수: {{ wrong_answers }}</p>
    {% if is_passed %}
      <p class="text-success">합격입니다!</p>
    {% else %}
      <p class="text-danger">불합격입니다.</p>
    {% endif %}
    <a href="{% url 'hobt:index' %}" class="btn btn-primary">돌아가기</a>
  </div>
{% endblock %}